#!/usr/bin/env python3
# TDLR Renewal Targeting - targets licenses expiring in 60-90 days.
# Contractors need to renew their bond at the same time as their TDLR license.
# Cron: 0 8 * * 1 (Mondays 8 AM)
# Usage: tdlr_renewal_target.py [--dry-run]
import os, sys
from datetime import datetime, date
import psycopg2

def _load_env(path="/usr/local/etc/qs-crm.env"):
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    os.environ.setdefault(k.strip(), v.strip())
    except OSError:
        pass

_load_env()
DRY_RUN = "--dry-run" in sys.argv
DB_URL = ("postgresql://quantum_user:" + os.environ["CRM_DB_PASSWORD"]
          + "@localhost:5433/quantum_surety")
BATCH_LIMIT = 500
TARGET_LICENSE_TYPES = [
    "Electrical Contractor",
    "Air Conditioning and Refrigeration Contractor",
    "Air Conditioning Contractor",
    "HVAC Contractor",
    "Plumbing Contractor",
    "Master Plumber",
    "Master Electrician",
    "Journeyman Electrician",
    "Elevator Contractor",
    "Water Well Driller/Pump Installer",
    "General Contractor",
    "Roofing Contractor",
    "Boiler Contractor",
    "Electrical Sign Contractor",
    "Residential Appliance Installer",
]

SELECT_SQL = """
SELECT t.business_name, t.business_phone, t.license_number, t.license_type,
       t.business_county, t.expire_date
FROM tdlr_licenses t
WHERE t.business_phone IS NOT NULL AND t.business_phone <> ''
  AND t.license_type = ANY(%s)
  AND t.expire_date BETWEEN CURRENT_DATE + INTERVAL '60 days'
                        AND CURRENT_DATE + INTERVAL '90 days'
  AND NOT EXISTS (
    SELECT 1 FROM leads l
    WHERE regexp_replace(l.phone, '\\D', '', 'g') = regexp_replace(t.business_phone, '\\D', '', 'g')
      AND l.phone <> ''
      AND l.created_at >= NOW() - INTERVAL '30 days'
  )
ORDER BY t.expire_date ASC
LIMIT %s
"""

INSERT_SQL = """
INSERT INTO leads (name, email, phone, bond_type, source, status, notes, created_at, updated_at)
VALUES (%s, '', %s, 'Texas Contractor License Bond', 'TDLR Renewal Target', 'new', %s, NOW(), NOW())
"""

def main():
    conn = psycopg2.connect(DB_URL)
    cur = conn.cursor()
    cur.execute(SELECT_SQL, (TARGET_LICENSE_TYPES, BATCH_LIMIT))
    rows = cur.fetchall()
    today = date.today()
    print("[%s] %d expiring licenses found for renewal targeting%s" % (
        datetime.now(), len(rows), " (DRY RUN)" if DRY_RUN else ""))

    inserted = 0
    for name, phone, lic_no, lic_type, county, expires in rows:
        days = (expires - today).days if expires else "?"
        notes = ("TDLR License: %s #%s\nCounty: %s\nLicense expires: %s\nDays until expiry: %s\n"
                 "Lead auto-generated by TDLR Renewal Target (bond renewal reminder)" % (
                     lic_type or "Unknown", lic_no, county or "Unknown", expires, days))
        if DRY_RUN:
            if inserted < 5:
                print("  would insert: %s | %s | %s expires %s (%sd)" % (name, phone, lic_type, expires, days))
            inserted += 1
            continue
        try:
            cur.execute(INSERT_SQL, (name, phone, notes))
            conn.commit()
            inserted += 1
        except Exception as e:
            print("  insert error for %s: %s" % (name, e))
            conn.rollback()

    print("[%s] %s %d leads" % (datetime.now(), "would insert" if DRY_RUN else "inserted", inserted))
    cur.close()
    conn.close()

if __name__ == "__main__":
    main()
