#!/usr/bin/env python3
"""
TDLR contractor monitor — rebuilt 2026-06-10 (original lost to /tmp cleanup).
Runs monthly on the 2nd, the day after import_tdlr_licenses.py refreshes the
tdlr_licenses table. Creates CRM leads for recently issued/renewed Electrical
Contractor licenses (expire_date 8-13 months out matches the observed behavior
of the original: June 2026 batch covered expiries 2027-02-13 .. 2027-06-13).
Dedupes against existing lead phone numbers.

Usage: tdlr_monitor.py [--dry-run]
Cron: 0 9 2 * *
"""

import os
import sys
from datetime import datetime

import psycopg2


def _load_env(path="/usr/local/etc/qs-crm.env"):
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    os.environ.setdefault(k.strip(), v.strip())
    except OSError:
        pass


_load_env()
DB_URL = ("postgresql://quantum_user:" + os.environ["CRM_DB_PASSWORD"]
          + "@localhost:5433/quantum_surety")
LICENSE_TYPE = "Electrical Contractor"
BATCH_LIMIT = 3000
DRY_RUN = "--dry-run" in sys.argv

SELECT_SQL = """
SELECT t.business_name, t.business_phone, t.license_number, t.license_type,
       t.business_county, t.expire_date
FROM tdlr_licenses t
WHERE t.license_type = %s
  AND t.business_phone IS NOT NULL AND t.business_phone <> ''
  AND t.expire_date BETWEEN CURRENT_DATE + INTERVAL '8 months'
                        AND CURRENT_DATE + INTERVAL '13 months'
  AND NOT EXISTS (
    SELECT 1 FROM leads l
    WHERE regexp_replace(l.phone, '\\D', '', 'g') = regexp_replace(t.business_phone, '\\D', '', 'g')
      AND l.phone <> ''
  )
ORDER BY t.expire_date DESC
LIMIT %s
"""

INSERT_SQL = """
INSERT INTO leads (name, email, phone, bond_type, source, status, notes, created_at, updated_at)
VALUES (%s, '', %s, 'Texas Contractor License Bond', 'TDLR Monitor', 'new', %s, NOW(), NOW())
"""


def main():
    conn = psycopg2.connect(DB_URL)
    cur = conn.cursor()
    cur.execute(SELECT_SQL, (LICENSE_TYPE, BATCH_LIMIT))
    rows = cur.fetchall()
    print(f"[{datetime.now()}] {len(rows)} new {LICENSE_TYPE} licenses to convert to leads"
          + (" (DRY RUN)" if DRY_RUN else ""))

    inserted = 0
    for name, phone, lic_no, lic_type, county, expires in rows:
        notes = (f"TDLR License: {lic_type} #{lic_no}\n"
                 f"County: {county or 'Unknown'}\n"
                 f"License expires: {expires}\n"
                 f"Lead auto-generated by TDLR monitor")
        if DRY_RUN:
            if inserted < 5:
                print(f"  would insert: {name} | {phone} | expires {expires}")
            inserted += 1
            continue
        try:
            cur.execute(INSERT_SQL, (name, phone, notes))
            inserted += 1
        except Exception as e:
            print(f"  insert error for {name}: {e}")
            conn.rollback()
        else:
            conn.commit()

    print(f"[{datetime.now()}] {'would insert' if DRY_RUN else 'inserted'} {inserted} leads")
    cur.close()
    conn.close()


if __name__ == "__main__":
    main()
